### DISCUSSION TITLE
Install problem

### DISCUSSION THREAD

**Discussion by davelowe1977** [Xyphyn/photon#481] [Q&A]
I followed these instructions:

"Self-hosting

Put Photon on your own domain for easier onboarding.
Running from image

Use the env var PUBLIC_INSTANCE_URL to set the default instance URL.
docker run -p 8080:3000 -e PUBLIC_INSTANCE_URL=example.com ghcr.io/xyphyn/photon:latest
"

On Ubuntu 22.04.5 LTS
I changed PUBLIC_INSTANCE_URL to point to a a reachable subdomain
I setup my reverse proxy (NGINX) to point to lemmyip:8080
I can open the homepage on my instance but get:
"500
TypeError: NetworkError when attempting to fetch resource."

What have I done wrong?

**Comment by davelowe1977** [comment]
Seems to be this problem:
https://github.com/Xyphyn/photon/issues/472
judging from the cors errors in the browser console

**Comment by davelowe1977** [comment]
I have repeated the exercise of installing using the dev and production instructions on a VM with a GUI so I can try opening 0,0.0.0:8080 without the complication of a reverse proxy. Still doesn't work either with the docker container or by the latest docker. Has anyone but devs actually got an instance of this running?

**Comment by sevonj** [comment]
There are a couple instances that serve photon as default.

Here's a known working configuration, with some irrelevant stuff removed:

`docker-compose.yml`
```yaml
services:
  photon_ui:
    container_name: photon
    image: "ghcr.io/xyphyn/photon:latest"
    ports:
      - 127.0.0.1:3000:3000
    env_file: photon_ui.env
    restart: always
```

`photon_ui.env`
```
# Instance
PUBLIC_INSTANCE_URL=target-instance-here.com
PUBLIC_LOCK_TO_INSTANCE=true
```

Edit: try `PUBLIC_INSTANCE_URL=lemmy.world` to rule out your instance being the problem
