### ISSUE TITLE
Feature Request: Option to disable unnecessary blur in interface

### ISSUE THREAD

**Issue by OleksiiGrinka** [Xyphyn/photon#602]
**Is your feature request related to a problem? Please describe.**
I find that it's hard to perceive dynamic blur for me, I think there is many people who find it hard too

**Describe the solution you'd like**
An option to disable unnecessary blur in interface, this includes parts that can change dynamically like top bar but not blurred NSFW images

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Xyphyn** [comment]
a setting for this is not something i will add, but using an extension like Stylus, you can add these css rules:

```css
:root {
  --blur-sm: 0px !important;
  --blur-md: 0px !important;
  --blur-lg: 0px !important;
  --blur-xl: 0px !important;
  --blur-2xl: 0px !important;
  --blur-3xl: 0px !important;
}
```
